### ISSUE TITLE
Does this works on flink-1.12.1?

### ISSUE THREAD

**Issue by louisliu318** [findify/flink-adt#17]
Does this works on flink-1.12.1?

**Comment by shuttie** [comment]
It depends on how you define “works”. Only Flink 1.15 is Scala free (so flink-adt can be used with Scala 3, for example). Right now this library is exclusively for 1.15 and cannot be backported to earlier versions.

Flink 1.12 is Scala 2.12 only, so technically some older versions of this library (like 0.4.x) could be rebuilt with flink 2.12, but I don’t see much reason to spend time supporting EOLed version of flink. Time to upgrade! :)

**Comment by louisliu318** [comment]
@shuttie thanks for your advice. I will try to upgrade flink to 1.15.
